import type { Checkpoint, Mission, MissionId } from './types';

function checkpoint(
  id: string,
  stage: string,
  title: string,
  action: string,
  recoveryAction: string,
  minutes: number,
  criteria: string[],
): Checkpoint {
  return { id, stage, title, action, recoveryAction, minutes, criteria };
}

function starter(mission: Omit<Mission, 'owner' | 'roadmapVersion' | 'planned'>): Mission {
  return {
    ...mission,
    description: `${mission.description} Authored prototype starter, not a complete canonical curriculum.`,
    owner: 'Your workspace',
    roadmapVersion: '1.0.0',
    planned: false,
  };
}

// Dependencies are related support links. Only checkpoint order gates progress.
export const missions: Mission[] = [
  starter({
    id: 'pattern',
    name: 'DSA',
    operation: 'Pattern Forge',
    description: 'Practice reusable problem-solving patterns with small, explainable solutions.',
    purpose: 'Recognize a pattern, explain the trade-off, and test the solution.',
    color: 'sage',
    icon: 'code',
    dependencies: ['system'],
    checkpoints: [
      checkpoint('pattern-arrays', 'Find the pattern', 'Arrays and lookup maps',
        'Solve a pair-sum example with a lookup map.',
        'Trace a lookup map on one tiny pair-sum example.', 25,
        ['Explain why the lookup works.', 'Test duplicates and a no-match input.', 'State time and space costs.']),
      checkpoint('pattern-window', 'Find the pattern', 'Two pointers and windows',
        'Solve a short sliding-window problem and explain the invariant.',
        'Write the window invariant and trace three steps.', 25,
        ['Explain when each pointer moves.', 'Test an empty input and a shrinking window.']),
      checkpoint('pattern-trees', 'Explore structure', 'Tree traversal',
        'Implement a traversal and compare depth-first with breadth-first search.',
        'Draw a tiny tree and list its traversal order.', 30,
        ['Show a correct traversal on an uneven tree.', 'Explain stack or queue space.']),
      checkpoint('pattern-graphs', 'Explore structure', 'Graph search',
        'Find a path through a small graph with a visited set.',
        'Mark visited nodes on a four-node graph.', 30,
        ['Handle a cycle and an unreachable node.', 'Explain why each node is visited once.']),
      checkpoint('pattern-review', 'Retrieve and explain', 'Mixed-pattern rehearsal',
        'Re-solve a previous problem without notes and explain your choice.',
        'Recall one pattern and the clue that suggests it.', 35,
        ['Choose a pattern before coding.', 'Test the solution and record one improvement.']),
    ],
  }),
  starter({
    id: 'system',
    name: 'System Design',
    operation: 'System Forge',
    description: 'Turn an ambiguous product idea into a small, defensible system design.',
    purpose: 'Make requirements, failure modes, and trade-offs visible.',
    color: 'blue',
    icon: 'layers',
    dependencies: ['pattern', 'blueprint'],
    checkpoints: [
      checkpoint('system-scope', 'Frame the problem', 'Requirements and scale',
        'Scope a fictional link-saving service and estimate its traffic.',
        'Write one user flow and one scale assumption.', 30,
        ['Separate functional needs from quality goals.', 'State assumptions and one rough capacity estimate.']),
      checkpoint('system-shape', 'Design the flow', 'API and data model',
        'Sketch the write and read paths for the link-saving service.',
        'Sketch one request from client to storage.', 30,
        ['Define the main API and stored fields.', 'Explain an indexing or consistency choice.']),
      checkpoint('system-resilience', 'Design the flow', 'Failure and recovery',
        'Walk through a timeout and a duplicate request in the design.',
        'Name one failure and a safe response.', 25,
        ['Explain a bounded retry and timeout policy.', 'Show how duplicate writes are handled.']),
      checkpoint('system-scale', 'Defend the design', 'Scaling trade-offs',
        'Compare a cache and a queue against the service requirements.',
        'Write one benefit and one cost of caching.', 35,
        ['Identify the bottleneck each option addresses.', 'Describe stale data or backpressure behavior.']),
      checkpoint('system-rehearse', 'Defend the design', 'Design walkthrough',
        'Present the design from requirements through a failure scenario.',
        'Give a two-minute summary of the main trade-off.', 40,
        ['Connect design choices to the original goals.', 'Record feedback and revise one weak point.']),
    ],
  }),
  starter({
    id: 'escape',
    name: 'Career opportunities',
    operation: 'Escape Velocity',
    description: 'Connect role discovery, clear evidence, and thoughtful interview preparation.',
    purpose: 'Keep opportunities organized without equating activity with readiness.',
    color: 'amber',
    icon: 'rocket',
    dependencies: ['pattern', 'system', 'neural'],
    checkpoints: [
      checkpoint('escape-target', 'Find direction', 'Role signals',
        'Compare two example role descriptions and note recurring skills.',
        'Highlight one skill in an example role description.', 20,
        ['Name the role scope and desired capabilities.', 'Separate required skills from optional signals.']),
      checkpoint('escape-evidence', 'Build the story', 'Evidence-backed profile',
        'Draft one profile bullet using a project you can explain.',
        'Outline one contribution and its supporting artifact.', 20,
        ['Connect the contribution to a verifiable artifact.', 'Avoid invented impact or unsupported metrics.']),
      checkpoint('escape-stories', 'Build the story', 'Situation-to-result story',
        'Outline a concise situation, task, action, and result story.',
        'Write the situation and one specific action.', 25,
        ['Distinguish your actions from team context.', 'Include an honest outcome and a lesson.']),
      checkpoint('escape-pipeline', 'Practice and follow through', 'Opportunity next step',
        'Review one saved opportunity and choose a concrete next step.',
        'Write one question to clarify role fit.', 20,
        ['Record the current stage and a source link if available.', 'Name a next action without assuming an outcome.']),
      checkpoint('escape-rehearsal', 'Practice and follow through', 'Interview rehearsal',
        'Practice a project walkthrough and capture a follow-up question.',
        'Explain one project decision in two minutes.', 30,
        ['Explain a decision, trade-off, and lesson.', 'Record one gap to revisit; assess readiness separately.']),
    ],
  }),
  starter({
    id: 'fabric',
    name: 'Service Fabric',
    operation: 'Fabric Core',
    description: 'Explore Service Fabric concepts through diagrams and safe local exercises.',
    purpose: 'Reason about placement, state, health, and recovery before operating a cluster.',
    color: 'rose',
    icon: 'network',
    dependencies: ['system'],
    checkpoints: [
      checkpoint('fabric-model', 'Build the model', 'Cluster and service map',
        'Map nodes, applications, services, partitions, and replicas.',
        'Draw one service and its replicas across nodes.', 25,
        ['Distinguish the main resource boundaries.', 'Explain a stateless instance versus a stateful replica.']),
      checkpoint('fabric-state', 'Build the model', 'State and failover',
        'Trace a stateful partition through a primary replica failure.',
        'Label primary and secondary replicas in a sketch.', 30,
        ['Explain replication and quorum at a conceptual level.', 'Describe availability when a replica is lost.']),
      checkpoint('fabric-local', 'Try it safely', 'Local service exercise',
        'Inspect or run a sample service in an isolated local environment.',
        'Read a sample service entry point and summarize it.', 35,
        ['Explain the service lifecycle from the sample.', 'Capture a local observation without production access.']),
      checkpoint('fabric-health', 'Try it safely', 'Health and upgrades',
        'Outline a health-gated rolling upgrade for the sample service.',
        'List one health signal that should pause an upgrade.', 30,
        ['Explain upgrade domains and health checks.', 'Describe a safe rollback or stop condition.']),
      checkpoint('fabric-recovery', 'Explain operations', 'Recovery tabletop',
        'Walk through a fictional unhealthy-partition scenario.',
        'List the first two observations to collect.', 30,
        ['Separate symptoms from a root-cause hypothesis.', 'Choose a safe diagnostic step and verification signal.']),
    ],
  }),
  starter({
    id: 'blueprint',
    name: 'Software Architecture',
    operation: 'Blueprint',
    description: 'Practice architecture as explicit boundaries, decisions, and quality trade-offs.',
    purpose: 'Create small design artifacts that explain why a system is shaped this way.',
    color: 'violet',
    icon: 'compass',
    dependencies: ['system', 'fabric'],
    checkpoints: [
      checkpoint('blueprint-context', 'Discover boundaries', 'System context',
        'Draw a context map for a fictional booking application.',
        'Name its users and one external dependency.', 25,
        ['Identify users, ownership, and external systems.', 'State what is outside the system boundary.']),
      checkpoint('blueprint-modules', 'Discover boundaries', 'Module responsibilities',
        'Split the booking application into a few cohesive modules.',
        'Give one module a single clear responsibility.', 30,
        ['Define responsibilities and data ownership.', 'Show allowed dependency directions.']),
      checkpoint('blueprint-decision', 'Record decisions', 'Architecture decision',
        'Write a short decision record comparing two design options.',
        'List one option and its main downside.', 25,
        ['Record context, alternatives, and a chosen option.', 'Explain consequences and a revisit trigger.']),
      checkpoint('blueprint-quality', 'Test the design', 'Quality scenario',
        'Test the design against a concrete reliability or change scenario.',
        'Describe one measurable quality goal.', 30,
        ['Specify a stimulus and expected response.', 'Identify a design weakness and a mitigation.']),
      checkpoint('blueprint-evolution', 'Test the design', 'Evolution plan',
        'Plan a small architecture change with a reversible rollout.',
        'Name one compatibility risk in the change.', 35,
        ['Protect an existing consumer or data contract.', 'Define rollout checks and a rollback path.']),
    ],
  }),
  starter({
    id: 'credential',
    name: 'Certifications',
    operation: 'Credential Forge',
    description: 'Capability path: Cloud foundations, cloud administration, cloud development, architecture, AI. Choose current credentials separately; no exam is mandated.',
    purpose: 'Build demonstrable capabilities and verify current certification requirements when needed.',
    color: 'sand',
    icon: 'award',
    dependencies: ['fabric', 'neural'],
    checkpoints: [
      checkpoint('credential-foundations', 'Cloud foundations', 'Cloud foundations',
        'Compare cloud service models and shared responsibility.',
        'Explain one shared-responsibility boundary.', 25,
        ['Match a workload to a service model.', 'Explain cost, identity, and responsibility basics.']),
      checkpoint('credential-administration', 'Operate and build', 'Cloud administration',
        'Outline a sandbox resource setup with identity and cost controls.',
        'List one least-privilege role and one cost guardrail.', 30,
        ['Describe access, networking, and monitoring choices.', 'Include cleanup and a budget safeguard.']),
      checkpoint('credential-development', 'Operate and build', 'Cloud development',
        'Design a small cloud-backed API with managed identity.',
        'Sketch how the API authenticates to storage.', 30,
        ['Explain configuration and secret-free authentication.', 'Define a test and a useful diagnostic signal.']),
      checkpoint('credential-architecture', 'Design and apply', 'Architecture',
        'Compare two cloud deployment options for a sample workload.',
        'Write one availability-versus-cost trade-off.', 35,
        ['Compare reliability, cost, and operational complexity.', 'Record assumptions and a recovery approach.']),
      checkpoint('credential-ai', 'Design and apply', 'AI',
        'Outline a responsible AI feature and check current learning options.',
        'Name one AI failure mode and an evaluation example.', 30,
        ['Define an evaluation and a data-safety boundary.', 'Verify current official requirements before choosing an optional credential.']),
    ],
  }),
  starter({
    id: 'neural',
    name: 'AI Engineering',
    operation: 'Neural Edge',
    description: 'Build a small AI feature with evaluation, safe data handling, and operational limits.',
    purpose: 'Measure useful behavior instead of relying on an impressive demo.',
    color: 'teal',
    icon: 'cpu',
    dependencies: ['pattern', 'system'],
    checkpoints: [
      checkpoint('neural-frame', 'Frame and measure', 'Task and baseline',
        'Define a fictional support-labeling task with synthetic examples.',
        'Write one synthetic input and its expected label.', 25,
        ['Define the task and a non-AI baseline.', 'Create a small synthetic evaluation set.']),
      checkpoint('neural-evaluate', 'Frame and measure', 'Prompt and evaluation',
        'Compare two prompts against the same evaluation examples.',
        'Inspect one wrong answer and label the failure.', 30,
        ['Record repeatable evaluation criteria.', 'Compare errors, not just a successful example.']),
      checkpoint('neural-retrieval', 'Build a bounded feature', 'Grounded retrieval',
        'Sketch retrieval from a small public or synthetic document set.',
        'Trace one answer back to its source passage.', 35,
        ['Show how retrieved context supports the answer.', 'Handle missing evidence without inventing facts.']),
      checkpoint('neural-safety', 'Build a bounded feature', 'Safety and boundaries',
        'Test the feature with an unsafe instruction and sensitive-data example.',
        'Write one synthetic adversarial test case.', 30,
        ['Keep untrusted content separate from instructions.', 'Define data minimization and a safe failure response.']),
      checkpoint('neural-operate', 'Observe and improve', 'Operational review',
        'Define latency, cost, and quality checks for the AI feature.',
        'Choose one quality signal and a fallback behavior.', 35,
        ['Set a budget and a bounded failure policy.', 'Describe monitoring and an evaluation-based release check.']),
    ],
  }),
  {
    id: 'algorithm',
    name: 'Competitive programming',
    operation: 'Algorithm Forge',
    description: 'Planned. No canonical roadmap has been supplied, so no checkpoints are invented.',
    purpose: 'Reserve a home for a future, explicitly selected competitive-programming roadmap.',
    color: 'gray',
    icon: 'trophy',
    owner: 'Your workspace',
    roadmapVersion: '1.0.0',
    planned: true,
    dependencies: ['pattern'],
    checkpoints: [],
  },
];

export function getMission(id: MissionId): Mission {
  const mission = missions.find((candidate) => candidate.id === id);
  if (!mission) throw new Error(`Unknown mission: ${id}`);
  return mission;
}
