import type { Mission } from '../types';
import { defineOperation } from '../operationBuilder';

// Sources are cited by filename/section/page only. No original PDFs are published here.
const PATTERN_DOC = 'Operation_Pattern_Forge_Career_HQ_Handoff.pdf';
const SYSTEM_DOC = 'Operation_System_Forge_Career_HQ_Handoff.pdf';
const FABRIC_DOC = 'Operation_Fabric_Core_Career_HQ_Handoff.pdf';

const patternMission: Mission = defineOperation({
  id: 'pattern',
  name: 'DSA',
  operation: 'Pattern Forge',
  description: 'HashMap mastery objective: fundamentals, then seen-before, frequency, complement, and grouping patterns.',
  purpose: 'Recognize a HashMap-based pattern, explain why the lookup works, and teach it back without notes.',
  color: 'sage',
  icon: 'code',
  owner: 'DSA Coach',
  dependencies: ['system'],
  sources: [
    { document: PATTERN_DOC, section: 'Section 3: Roadmap - Stage 1 HashMap Fundamentals', page: 1 },
    { document: PATTERN_DOC, section: 'Section 3: Roadmap - Stage 2 HashMap Pattern Mastery', page: 2 },
  ],
  sourceNotes: [
    'The latest handoff (Section 3) is HashMap-first and overwrites an older, fuller visual pattern taxonomy; only the HashMap objective is tracked as active checkpoints here.',
    'Future techniques mentioned in the handoff (Two Pointers, Sliding Window, Prefix Sum, Stack, Queue/Deque, Binary Search, Linked Lists, Trees, Graphs, Dynamic Programming) are not active HashMap checkpoints; they are kept as a future reference group only.',
    'An older visual roadmap used conflicting numbering (for example a visual 2.3 Two Pointers) instead of 2.3 Complement Lookup. That old numbering is retained below as historical reference only; no progress was imported from it.',
    'HashMap Fundamentals has no formal source checkpoint number. SourceId is included only for 2.1-2.4, which the handoff explicitly numbered.',
  ],
  resources: [
    { label: '389. Find the Difference', url: 'https://leetcode.com/problems/find-the-difference/' },
    { label: '451. Sort Characters By Frequency', url: 'https://leetcode.com/problems/sort-characters-by-frequency/' },
    { label: '347. Top K Frequent Elements', url: 'https://leetcode.com/problems/top-k-frequent-elements/' },
    { label: '692. Top K Frequent Words', url: 'https://leetcode.com/problems/top-k-frequent-words/' },
    { label: '438. Find All Anagrams in a String', url: 'https://leetcode.com/problems/find-all-anagrams-in-a-string/' },
  ],
  referenceGroups: [
    {
      title: 'Future DSA Techniques (Not Active HashMap Checkpoints)',
      kind: 'future',
      items: [
        { title: 'Two Pointers', detail: 'Mentioned as a future objective; no checkpoint is unlocked yet.' },
        { title: 'Sliding Window', detail: 'Mentioned as a future objective; no checkpoint is unlocked yet.' },
        { title: 'Prefix Sum', detail: 'Mentioned as a future objective; combines with HashMap in later problems but is not an active HashMap node.' },
        { title: 'Stack', detail: 'Mentioned as a future objective; no checkpoint is unlocked yet.' },
        { title: 'Queue / Deque', detail: 'Mentioned as a future objective; no checkpoint is unlocked yet.' },
        { title: 'Binary Search', detail: 'Mentioned as a future objective; no checkpoint is unlocked yet.' },
        { title: 'Linked Lists', detail: 'Mentioned as a future objective; no checkpoint is unlocked yet.' },
        { title: 'Trees', detail: 'Mentioned as a future objective; no checkpoint is unlocked yet.' },
        { title: 'Graphs', detail: 'Mentioned as a future objective; no checkpoint is unlocked yet.' },
        { title: 'Dynamic Programming', detail: 'Mentioned as a future objective; no checkpoint is unlocked yet.' },
      ],
    },
    {
      title: 'Legacy Visual Roadmap (Historical Reference Only)',
      kind: 'forecast',
      items: [
        { title: 'Older generic DSA sequence', detail: 'An earlier Executive Summary roadmap began with Sliding Window / Two Pointers rather than HashMap; retained for long-term context only, with no automatic progress imported.' },
        { title: 'Conflicting checkpoint numbering', detail: 'The old visual numbering (for example a visual "2.3 Two Pointers") conflicts with this handoff\'s 2.3 Complement Lookup; the handoff numbering is canonical.' },
      ],
    },
  ],
  stages: [
    {
      id: 'hashmap-fundamentals',
      title: 'HashMap Fundamentals',
      summary: 'Core HashMap vocabulary and C# Dictionary operations before pattern work begins.',
      topics: ['C# Dictionary', 'Key-value pairs', 'Add and update elements', 'ContainsKey', 'map[key] indexer', 'O(1) lookup intuition'],
      source: { document: PATTERN_DOC, section: 'Section 3: Roadmap - Stage 1 HashMap Fundamentals', page: 1 },
      checkpoints: [
        {
          id: 'fundamentals',
          title: 'HashMap Fundamentals',
          action: 'Implement add, update, and ContainsKey lookup on a C# Dictionary, stopping once each operation runs correctly on a tiny example.',
          recoveryAction: 'Add one key-value pair to a Dictionary and read it back with the indexer.',
          minutes: 20,
          criteria: [
            'Explain key-value pairs and when ContainsKey avoids a missing-key error.',
            'Teach back add, update, and indexer lookup on a tiny example without notes.',
          ],
        },
      ],
    },
    {
      id: 'hashmap-pattern-mastery',
      title: 'HashMap Pattern Mastery',
      summary: 'Four HashMap pattern checkpoints: detect, count, find a complement, and group.',
      topics: ['Seen-before detection', 'Frequency counting', 'Complement lookup', 'Grouping by signature'],
      source: { document: PATTERN_DOC, section: 'Section 3: Roadmap - Stage 2 HashMap Pattern Mastery', page: 2 },
      checkpoints: [
        {
          id: '2-1',
          title: 'Seen Before',
          action: 'Solve a duplicate-detection problem with a HashSet or Dictionary, stopping once you can explain why each lookup is O(1).',
          recoveryAction: 'Trace one seen-before check on a four-element example.',
          minutes: 25,
          criteria: [
            'Explain why a seen-before set avoids a nested loop.',
            'Teach back the lookup cost for one example without referencing notes.',
          ],
          sourceId: '2.1',
        },
        {
          id: '2-2',
          title: 'Frequency Counting',
          action: 'Build a frequency map for a small input, stopping once every count matches a hand-traced expectation.',
          recoveryAction: 'Count occurrences in a five-element array by hand first.',
          minutes: 30,
          criteria: [
            'Explain the increment-or-initialize logic for a missing key.',
            'Teach back the frequency map result without looking at code.',
          ],
          sourceId: '2.2',
        },
        {
          id: '2-3',
          title: 'Complement Lookup',
          action: 'Solve a target-minus-current pair-lookup problem, stopping once duplicates and the no-match case are both handled.',
          recoveryAction: 'Trace one complement check on a four-number example.',
          minutes: 30,
          criteria: [
            'Explain why checking the complement before inserting avoids reusing one element twice.',
            'Teach back the approach for one duplicate or no-match edge case.',
          ],
          sourceId: '2.3',
          requires: ['2-2'],
        },
        {
          id: '2-4',
          title: 'Grouping',
          action: 'Group a small list of items by a derived key, such as a sorted-letters signature, stopping once every group is correct.',
          recoveryAction: 'Compute the signature for two example items by hand.',
          minutes: 30,
          criteria: [
            'Explain how the signature groups equivalent items together.',
            'Teach back how a new signature becomes a new map entry.',
          ],
          sourceId: '2.4',
          requires: ['2-2'],
        },
      ],
    },
  ],
});

const systemMission: Mission = defineOperation({
  id: 'system',
  name: 'System Design',
  operation: 'System Forge',
  description: 'Seven-stage backend and distributed-systems roadmap, grouped into four topic groups per stage.',
  purpose: 'Build systems thinking through explain-draw-exercise retention, not through memorized answers.',
  color: 'blue',
  icon: 'layers',
  owner: 'System Design Coach',
  dependencies: ['pattern', 'blueprint'],
  coverage: 'phase-level',
  sources: [
    { document: SYSTEM_DOC, section: 'Section 3: Roadmap - Stage 0 Foundation Setup', page: 2 },
    { document: SYSTEM_DOC, section: 'Section 3: Roadmap - Stage 1 Core Building Blocks', page: 2 },
    { document: SYSTEM_DOC, section: 'Section 3: Roadmap - Stage 2 Backend Architecture Patterns', page: 2 },
    { document: SYSTEM_DOC, section: 'Section 3: Roadmap - Stage 3 Distributed Systems Deep Dive', page: 2 },
    { document: SYSTEM_DOC, section: 'Section 3: Roadmap - Stage 4 Real-World System Design', page: 2 },
    { document: SYSTEM_DOC, section: 'Section 3: Roadmap - Stage 5 Cloud & Infrastructure', page: 3 },
    { document: SYSTEM_DOC, section: 'Section 3: Roadmap - Stage 6 AI-Integrated Systems', page: 3 },
    { document: 'Career_HQ_Operating_System.pdf', section: 'Canonical visual roadmap: System Forge', page: 115 },
  ],
  sourceNotes: [
    'Each checkpoint tracks a source topic group at topic-group granularity; the handoff did not number individual checkpoints, so sourceId is omitted throughout this mission.',
    'Criteria ask you to explain, draw, and finish a small design exercise, matching the source\'s own retention framework; exposure to a topic is not treated as retention.',
    'No personal save-state, status, or progress from the source handoff is imported here; only the stable topic groups are tracked.',
  ],
  referenceGroups: [
    {
      title: 'Continuous Supporting Activities',
      kind: 'projects',
      items: [
        { title: 'Build small projects', detail: 'Apply topic groups to a small, self-directed build rather than a new checkpoint.' },
        { title: 'Solve design exercises', detail: 'Practice exercises outside the tracked topic groups for extra repetition.' },
        { title: 'Read real-system case studies', detail: 'Study public case studies to ground abstract concepts in real systems.' },
        { title: 'Revise and make notes', detail: 'Periodic review of earlier topic groups, tracked informally.' },
        { title: 'Discuss tradeoffs', detail: 'Talk through design tradeoffs with a peer or mentor.' },
        { title: 'Stay current with industry trends', detail: 'Ongoing awareness activity, not a gating checkpoint.' },
      ],
    },
  ],
  stages: [
    {
      id: 'stage-0-foundation-setup',
      title: 'Stage 0 - Foundation Setup',
      summary: 'Refresh core CS basics, set up tools, adopt a system design mindset, and establish a learning ritual.',
      topics: ['OS basics', 'Networking basics', 'Database basics', 'Data structures as needed'],
      source: { document: SYSTEM_DOC, section: 'Section 3: Roadmap - Stage 0 Foundation Setup', page: 2 },
      checkpoints: [
        {
          id: 'refresh-cs-basics', title: 'Refresh Computer Science Basics',
          action: 'Explain, diagram, and finish one small exercise covering OS, networking, database, and data-structure basics until each is clear without notes.',
          recoveryAction: 'Re-read one basic topic and summarize it in two sentences.', minutes: 30,
          criteria: ['Explain each listed basic in your own words without notes.', 'Draw one relevant diagram (for example an OS process/thread view).', 'Finish one small exercise applying at least two of these basics together.'],
          topics: ['Operating systems', 'Networking', 'Databases', 'Data structures'], granularity: 'topic-group',
        },
        {
          id: 'development-tools-setup', title: 'Development & Tools Setup',
          action: 'Explain, diagram, and finish one small exercise covering Linux, command line, Git, and a cloud account until the setup is working end to end.',
          recoveryAction: 'Run one command-line and one Git command successfully.', minutes: 30,
          criteria: ['Explain what each tool (Linux, CLI, Git, cloud account) is for.', 'Diagram your local toolchain from editor to cloud account.', 'Finish one small exercise committing a change with Git.'],
          topics: ['Linux', 'Command line', 'Git / version control', 'Cloud account'], granularity: 'topic-group',
        },
        {
          id: 'system-design-mindset', title: 'System Design Mindset',
          action: 'Explain, diagram, and finish one small exercise covering systems thinking, decision making, non-functional requirements, and estimation until each is clear.',
          recoveryAction: 'List one functional and one non-functional requirement for a tiny example.', minutes: 25,
          criteria: ['Explain the difference between functional and non-functional requirements.', 'Draw a simple decision flow for choosing between two design options.', 'Finish one small back-of-envelope estimation exercise.'],
          topics: ['Systems thinking', 'Decision making', 'Non-functional requirements', 'Back-of-envelope estimation'], granularity: 'topic-group',
        },
        {
          id: 'learning-ritual', title: 'Learning Ritual',
          action: 'Explain, diagram, and finish one small exercise covering the read-understand-draw-modify-explain ritual until you can repeat it unaided.',
          recoveryAction: 'Apply the ritual to one short article in five minutes.', minutes: 20,
          criteria: ['Explain each step of the read-understand-draw-modify-explain ritual.', 'Draw the ritual as a simple loop diagram.', 'Finish one small exercise applying the full ritual to a short topic.'],
          topics: ['Read-understand-draw-modify-explain', 'Notes and revision', 'Consistent practice'], granularity: 'topic-group',
        },
      ],
    },
    {
      id: 'stage-1-core-building-blocks',
      title: 'Stage 1 - Core Building Blocks',
      summary: 'Networking, compute and storage, databases, and caching fundamentals.',
      topics: ['Networking & protocols', 'Compute & storage', 'Databases', 'Caching'],
      source: { document: SYSTEM_DOC, section: 'Section 3: Roadmap - Stage 1 Core Building Blocks', page: 2 },
      checkpoints: [
        {
          id: 'networking-protocols', title: 'Networking & Protocols',
          action: 'Explain, diagram, and finish one small exercise covering TCP/IP, HTTP/HTTPS, DNS, load balancers, reverse proxy, and TLS until each is clear.',
          recoveryAction: 'Diagram one request going through DNS then to a server.', minutes: 35,
          criteria: ['Explain the request path from DNS lookup to an HTTP response.', 'Draw a load balancer and reverse proxy sitting in front of servers.', 'Finish one small exercise choosing a load-balancing strategy for a given scenario.'],
          topics: ['TCP/IP', 'HTTP/HTTPS', 'DNS', 'Load Balancers', 'Reverse Proxy / NGINX', 'SSL/TLS'], granularity: 'topic-group',
        },
        {
          id: 'compute-storage', title: 'Compute & Storage',
          action: 'Explain, diagram, and finish one small exercise covering servers/VMs, Docker, Kubernetes basics, and storage types until each is clear.',
          recoveryAction: 'Diagram one container running on one VM.', minutes: 30,
          criteria: ['Explain the difference between a VM and a container.', 'Draw a simple deployment using Docker and Kubernetes basics.', 'Finish one small exercise comparing object, block, and file storage for a scenario.'],
          topics: ['Servers / VMs', 'Docker', 'Kubernetes basics', 'Object storage', 'Block vs file storage'], granularity: 'topic-group',
        },
        {
          id: 'databases', title: 'Databases',
          action: 'Explain, diagram, and finish one small exercise covering SQL, NoSQL, indexing, and replication/sharding until each is clear.',
          recoveryAction: 'Write one SQL query and one reason to add an index.', minutes: 35,
          criteria: ['Explain when SQL or NoSQL fits a given workload.', 'Draw a simple sharded or replicated database layout.', 'Finish one small exercise explaining an indexing or CAP trade-off.'],
          topics: ['SQL', 'NoSQL', 'Indexing / query optimization', 'Replication / sharding', 'Practical CAP'], granularity: 'topic-group',
        },
        {
          id: 'caching', title: 'Caching',
          action: 'Explain, diagram, and finish one small exercise covering Redis, cache strategies, invalidation, and CDN basics until each is clear.',
          recoveryAction: 'State one cache invalidation strategy and its downside.', minutes: 25,
          criteria: ['Explain a cache strategy (for example cache-aside) and its invalidation approach.', 'Draw a request path that checks a cache before the database.', 'Finish one small exercise identifying stale-data risk in a caching design.'],
          topics: ['Redis', 'Cache strategies', 'Invalidation', 'CDN basics'], granularity: 'topic-group',
        },
      ],
    },
    {
      id: 'stage-2-backend-architecture-patterns',
      title: 'Stage 2 - Backend Architecture Patterns',
      summary: 'Application architecture, communication, scalability/reliability, and security/identity.',
      topics: ['Application architecture', 'Communication', 'Scalability & reliability', 'Security & identity'],
      source: { document: SYSTEM_DOC, section: 'Section 3: Roadmap - Stage 2 Backend Architecture Patterns', page: 2 },
      checkpoints: [
        {
          id: 'application-architecture', title: 'Application Architecture',
          action: 'Explain, diagram, and finish one small exercise covering monolith vs microservices, layered architecture, and REST/gRPC until each is clear.',
          recoveryAction: 'Draw one monolith and one microservice split for the same feature.', minutes: 30,
          criteria: ['Explain a tradeoff between a monolith and a microservice split.', 'Draw a layered architecture with clear service boundaries.', 'Finish one small exercise choosing REST or gRPC for a scenario.'],
          topics: ['Monolith vs microservices', 'Layered architecture', 'REST/gRPC', 'Service boundaries'], granularity: 'topic-group',
        },
        {
          id: 'communication', title: 'Communication',
          action: 'Explain, diagram, and finish one small exercise covering sync vs async, Kafka/SQS, and Pub/Sub until each is clear.',
          recoveryAction: 'Draw one synchronous call and one async message.', minutes: 30,
          criteria: ['Explain when sync or async communication fits a scenario.', 'Draw an event-driven flow using a queue or topic.', 'Finish one small exercise designing a Pub/Sub notification path.'],
          topics: ['Sync vs async', 'Kafka / SQS', 'Event-driven architecture', 'Pub/Sub'], granularity: 'topic-group',
        },
        {
          id: 'scalability-reliability', title: 'Scalability & Reliability',
          action: 'Explain, diagram, and finish one small exercise covering horizontal vs vertical scaling, statelessness, and consistency models until each is clear.',
          recoveryAction: 'State one reason horizontal scaling needs statelessness.', minutes: 30,
          criteria: ['Explain horizontal versus vertical scaling tradeoffs.', 'Draw a stateless service scaled across multiple instances.', 'Finish one small exercise choosing a consistency model for a scenario.'],
          topics: ['Horizontal vs vertical scaling', 'Stateless/stateful', 'Replication / fault tolerance', 'Consistency models'], granularity: 'topic-group',
        },
        {
          id: 'security-identity', title: 'Security & Identity',
          action: 'Explain, diagram, and finish one small exercise covering authentication/authorization, OAuth/JWT, and API security until each is clear.',
          recoveryAction: 'State the difference between authentication and authorization.', minutes: 30,
          criteria: ['Explain authentication versus authorization in a request flow.', 'Draw an OAuth/JWT token flow for one API call.', 'Finish one small exercise identifying one API security or secrets-handling risk.'],
          topics: ['Authentication / authorization', 'OAuth / JWT', 'API security', 'Secrets'], granularity: 'topic-group',
        },
      ],
    },
    {
      id: 'stage-3-distributed-systems-deep-dive',
      title: 'Stage 3 - Distributed Systems Deep Dive',
      summary: 'Distributed systems concepts, data/state management, fault tolerance, and observability.',
      topics: ['Distributed systems concepts', 'Data & state management', 'Fault tolerance', 'Observability'],
      source: { document: SYSTEM_DOC, section: 'Section 3: Roadmap - Stage 3 Distributed Systems Deep Dive', page: 2 },
      checkpoints: [
        {
          id: 'distributed-systems-concepts', title: 'Distributed Systems Concepts',
          action: 'Explain, diagram, and finish one small exercise covering consensus, leader election, distributed locks, and idempotency until each is clear.',
          recoveryAction: 'State why a retried request needs an idempotency key.', minutes: 35,
          criteria: ['Explain leader election and why consensus matters.', 'Draw a simple distributed-lock interaction between two nodes.', 'Finish one small exercise identifying an idempotency risk in a retried request.'],
          topics: ['Raft / consensus', 'Leader election', 'Distributed locks', 'Idempotency'], granularity: 'topic-group',
        },
        {
          id: 'data-state-management', title: 'Data & State Management',
          action: 'Explain, diagram, and finish one small exercise covering sharding, replication, partitioning, and event sourcing basics until each is clear.',
          recoveryAction: 'Draw one sharded dataset split across two partitions.', minutes: 35,
          criteria: ['Explain sharding versus replication for a dataset.', 'Draw a partitioned data layout with ownership per shard.', 'Finish one small exercise outlining an event-sourcing style state rebuild.'],
          topics: ['Sharding', 'Replication', 'Partitioning', 'Distributed transactions', 'Event sourcing basics'], granularity: 'topic-group',
        },
        {
          id: 'fault-tolerance', title: 'Fault Tolerance',
          action: 'Explain, diagram, and finish one small exercise covering failure modes, retries, circuit breakers, and bulkheads until each is clear.',
          recoveryAction: 'State one failure mode and a safe response.', minutes: 30,
          criteria: ['Explain a circuit breaker and when it trips.', 'Draw a bulkhead isolating one failing dependency.', 'Finish one small exercise designing a bounded retry policy.'],
          topics: ['Failure modes', 'Retries', 'Circuit breakers', 'Bulkheads', 'Graceful degradation'], granularity: 'topic-group',
        },
        {
          id: 'observability', title: 'Observability',
          action: 'Explain, diagram, and finish one small exercise covering logs, metrics, tracing, and SLOs/SLIs/SLAs until each is clear.',
          recoveryAction: 'State the difference between an SLI and an SLO.', minutes: 30,
          criteria: ['Explain how logs, metrics, and tracing differ and complement each other.', 'Draw a trace spanning two services for one request.', 'Finish one small exercise defining an SLI, SLO, and alert threshold for a service.'],
          topics: ['Logs', 'Metrics', 'Tracing', 'Monitoring / alerting', 'SLOs/SLIs/SLAs'], granularity: 'topic-group',
        },
      ],
    },
    {
      id: 'stage-4-real-world-system-design',
      title: 'Stage 4 - Real-World System Design',
      summary: 'Design fundamentals, common designs, advanced topics, and design interview structure.',
      topics: ['Design fundamentals', 'Common system designs', 'Advanced design topics', 'Design interviews'],
      source: { document: SYSTEM_DOC, section: 'Section 3: Roadmap - Stage 4 Real-World System Design', page: 2 },
      checkpoints: [
        {
          id: 'design-fundamentals', title: 'Design Fundamentals',
          action: 'Explain, diagram, and finish one small exercise covering requirements gathering, capacity estimation, and high-level design-first order until each is clear.',
          recoveryAction: 'Write one functional and one non-functional requirement for a prompt.', minutes: 30,
          criteria: ['Explain why high-level design should precede deep dives.', 'Draw a high-level design for a simple prompt.', 'Finish one small exercise estimating capacity for that design.'],
          topics: ['Requirements', 'Functional vs non-functional', 'Capacity estimation', 'High-level design first'], granularity: 'topic-group',
        },
        {
          id: 'common-system-designs', title: 'Common System Designs',
          action: 'Explain, diagram, and finish one small exercise covering a URL shortener, social feed, chat, or similar common design until it is complete.',
          recoveryAction: 'Sketch the write path for one common design.', minutes: 40,
          criteria: ['Explain the chosen common design\'s main components.', 'Draw its write and read paths.', 'Finish one small exercise describing one scaling bottleneck and mitigation.'],
          topics: ['URL shortener', 'Social feed', 'Chat', 'Ride sharing', 'Video streaming', 'E-commerce'], granularity: 'topic-group',
        },
        {
          id: 'advanced-design-topics', title: 'Advanced Design Topics',
          action: 'Explain, diagram, and finish one small exercise covering search, real-time, payments, or multi-region topics until one is clear.',
          recoveryAction: 'State one challenge unique to the chosen advanced topic.', minutes: 40,
          criteria: ['Explain why the chosen advanced topic is harder than a common design.', 'Draw one architecture addressing it.', 'Finish one small exercise identifying a tradeoff specific to that topic.'],
          topics: ['Search', 'Real-time systems', 'Payments', 'Multi-tenancy', 'Global multi-region', 'Large-scale processing'], granularity: 'topic-group',
        },
        {
          id: 'design-interviews', title: 'Design Interviews',
          action: 'Explain, diagram, and finish one small exercise covering clarify-design-deep dive-tradeoffs structure until you can run it unaided.',
          recoveryAction: 'List the four interview structure steps from memory.', minutes: 35,
          criteria: ['Explain each step of the clarify-design-deep dive-tradeoffs structure.', 'Draw a whiteboard-style design produced using that structure.', 'Finish one small timed exercise running the full structure end to end.'],
          topics: ['Structured approach', 'Whiteboard / document design', 'Clarify-design-deep dive-tradeoffs'], granularity: 'topic-group',
        },
      ],
    },
    {
      id: 'stage-5-cloud-infrastructure',
      title: 'Stage 5 - Cloud & Infrastructure',
      summary: 'Cloud platforms, container orchestration, high availability/DR, and cost optimization.',
      topics: ['Cloud platforms', 'Container orchestration', 'High availability & DR', 'Cost & optimization'],
      source: { document: SYSTEM_DOC, section: 'Section 3: Roadmap - Stage 5 Cloud & Infrastructure', page: 3 },
      checkpoints: [
        {
          id: 'cloud-platforms', title: 'Cloud Platforms',
          action: 'Explain, diagram, and finish one small exercise covering compute, storage, networking, managed databases, serverless, and infrastructure-as-code until each is clear.',
          recoveryAction: 'Name one compute and one storage service and their purpose.', minutes: 30,
          criteria: ['Explain the core compute, storage, and networking service categories.', 'Draw a simple architecture using a managed database and serverless function.', 'Finish one small exercise outlining an infrastructure-as-code plan for it.'],
          topics: ['Core cloud services', 'Compute / storage / networking', 'Managed databases', 'Serverless', 'Infrastructure as code'], granularity: 'topic-group',
        },
        {
          id: 'container-orchestration', title: 'Container Orchestration',
          action: 'Explain, diagram, and finish one small exercise covering Kubernetes, service discovery, ingress/load balancing, and autoscaling until each is clear.',
          recoveryAction: 'Draw one pod behind one ingress.', minutes: 35,
          criteria: ['Explain service discovery and ingress routing in Kubernetes.', 'Draw an autoscaling deployment behind a load balancer.', 'Finish one small exercise comparing two deployment strategies.'],
          topics: ['Kubernetes in depth', 'Service discovery', 'Ingress / load balancing', 'Autoscaling', 'Deployment strategies'], granularity: 'topic-group',
        },
        {
          id: 'high-availability-dr', title: 'High Availability & DR',
          action: 'Explain, diagram, and finish one small exercise covering multi-AZ/multi-region, backup/restore, and chaos engineering basics until each is clear.',
          recoveryAction: 'State one difference between multi-AZ and multi-region.', minutes: 30,
          criteria: ['Explain multi-AZ versus multi-region availability tradeoffs.', 'Draw a backup and restore flow for a critical dataset.', 'Finish one small exercise outlining a basic chaos-engineering experiment.'],
          topics: ['Multi-AZ / multi-region', 'Disaster recovery', 'Backup / restore', 'Chaos engineering basics'], granularity: 'topic-group',
        },
        {
          id: 'cost-optimization', title: 'Cost & Optimization',
          action: 'Explain, diagram, and finish one small exercise covering right-sizing, performance optimization, and operational best practices until each is clear.',
          recoveryAction: 'State one right-sizing opportunity for an over-provisioned resource.', minutes: 30,
          criteria: ['Explain a cost-versus-performance tradeoff in a design.', 'Draw where cost is incurred across a sample architecture.', 'Finish one small exercise proposing one right-sizing change.'],
          topics: ['Cost-aware architecture', 'Right sizing', 'Performance optimization', 'Operational best practices'], granularity: 'topic-group',
        },
      ],
    },
    {
      id: 'stage-6-ai-integrated-systems',
      title: 'Stage 6 - AI-Integrated Systems',
      summary: 'AI system fundamentals, integration patterns, AI scalability, and real-world AI products.',
      topics: ['AI system fundamentals', 'Integration patterns', 'Scalability for AI', 'Real-world AI products'],
      source: { document: SYSTEM_DOC, section: 'Section 3: Roadmap - Stage 6 AI-Integrated Systems', page: 3 },
      checkpoints: [
        {
          id: 'ai-system-fundamentals', title: 'AI System Fundamentals',
          action: 'Explain, diagram, and finish one small exercise covering AI/ML service types, inference versus training, and AI infrastructure until each is clear.',
          recoveryAction: 'State the difference between training and inference.', minutes: 30,
          criteria: ['Explain inference versus training at an architecture level.', 'Draw where an AI/ML service sits in a request flow.', 'Finish one small exercise identifying one infrastructure need for serving inference.'],
          topics: ['AI/ML service types', 'Inference vs training', 'AI infrastructure'], granularity: 'topic-group',
        },
        {
          id: 'integration-patterns', title: 'Integration Patterns',
          action: 'Explain, diagram, and finish one small exercise covering AI service calls, async processing, and RAG basics until each is clear.',
          recoveryAction: 'Draw one synchronous AI service call.', minutes: 30,
          criteria: ['Explain when an AI call should be asynchronous or long-running.', 'Draw a basic retrieval-augmented generation flow.', 'Finish one small exercise designing a long-running AI job handoff.'],
          topics: ['AI service calls', 'Async processing', 'Long-running jobs', 'RAG basics'], granularity: 'topic-group',
        },
        {
          id: 'scalability-ai', title: 'Scalability for AI Systems',
          action: 'Explain, diagram, and finish one small exercise covering queuing/rate limiting and cost/latency optimization until each is clear.',
          recoveryAction: 'State one reason to rate-limit an AI endpoint.', minutes: 30,
          criteria: ['Explain queuing and rate limiting for AI workloads.', 'Draw a caching layer for repeated AI responses.', 'Finish one small exercise proposing one cost/latency optimization.'],
          topics: ['Queuing / rate limiting', 'Cost/latency optimization', 'Caching AI responses'], granularity: 'topic-group',
        },
        {
          id: 'real-world-ai-products', title: 'Real-World AI Products',
          action: 'Explain, diagram, and finish one small exercise covering AI search, assistants, content generation, and safety/guardrails basics until each is clear.',
          recoveryAction: 'Name one guardrail you would add to an AI assistant.', minutes: 35,
          criteria: ['Explain one real-world AI product category and its architecture.', 'Draw a safety/guardrail check in the request path.', 'Finish one small exercise identifying one multimodal or safety risk.'],
          topics: ['AI search', 'Assistants', 'Content generation', 'Multimodal applications', 'Safety / guardrails basics'], granularity: 'topic-group',
        },
      ],
    },
  ],
});

const fabricMission: Mission = defineOperation({
  id: 'fabric',
  name: 'Service Fabric',
  operation: 'Fabric Core',
  description: 'Five-stage, 32-checkpoint Service Fabric roadmap from foundation concepts to interview readiness.',
  purpose: 'Reason about placement, state, health, and recovery, then convert that capability into interview-ready knowledge.',
  color: 'rose',
  icon: 'network',
  owner: 'Service Fabric Coach',
  dependencies: ['system'],
  coverage: 'documented',
  completionLabel: 'Documented roadmap complete',
  sources: [
    { document: FABRIC_DOC, section: 'Section 3: Roadmap - Stage 1 Foundation', page: 2 },
    { document: FABRIC_DOC, section: 'Section 3: Roadmap - Stage 2 Core Development', page: 2 },
    { document: FABRIC_DOC, section: 'Section 3: Roadmap - Stage 3 Real-World Application', page: 3 },
    { document: FABRIC_DOC, section: 'Section 3: Roadmap - Stage 4 Advanced Topics', page: 3 },
    { document: FABRIC_DOC, section: 'Section 3: Roadmap - Stage 5 Interview & Career', page: 3 },
    { document: 'Career_HQ_Operating_System.pdf', section: 'Canonical visual roadmap: Fabric Core', page: 117 },
  ],
  sourceNotes: [
    'Stage 3 (Real-World Application) is tracked with generic, sanitized, local examples only; no actual employer system names, IDs, or cloud commands are issued here.',
    '5.7 Keep Learning is a bounded review checkpoint (review one update or changelog since your last pass), not a promise of infinite or complete learning.',
    'Continuous behaviors from the source (documentation, hands-on practice, learning from a team, staying updated) are supporting activities across stages, not separate checkpoints.',
    'This roadmap reflects source-documented stages and checkpoints only; no personal progress, employer details, or private architecture information is included.',
  ],
  referenceGroups: [
    {
      title: 'Continuous Supporting Behaviors',
      kind: 'parallel',
      items: [
        { title: 'Documentation', detail: 'Write short notes as you go; not a separate checkpoint.' },
        { title: 'Hands-on practice', detail: 'Reinforce each stage with extra local practice.' },
        { title: 'Learning from a team', detail: 'Use generic, sanitized discussion of design decisions.' },
        { title: 'Staying updated', detail: 'Track official Service Fabric and Azure updates over time.' },
      ],
    },
  ],
  stages: [
    {
      id: 'stage-1-foundation',
      title: 'Stage 1 - Foundation',
      summary: 'Understand the basics: why Service Fabric, core concepts, stateful/stateless, partitions/replicas, Explorer, and local setup.',
      topics: ['Why Service Fabric', 'Core concepts', 'Stateful vs stateless', 'Partitions and replicas', 'Service Fabric Explorer', 'Development environment setup'],
      source: { document: FABRIC_DOC, section: 'Section 3: Roadmap - Stage 1 Foundation', page: 2 },
      checkpoints: [
        {
          id: '1-1', title: '1.1 Why Service Fabric?',
          action: 'Compare Service Fabric to a plain VM/container deployment for a sample workload, stopping once you can state two reasons to choose it and one reason not to.',
          recoveryAction: 'List one use case where Service Fabric helps.', minutes: 20,
          criteria: ['Explain at least two scenarios where Service Fabric is a good fit.', 'Teach back one scenario where a simpler deployment is preferable.'],
          sourceId: '1.1',
        },
        {
          id: '1-2', title: '1.2 Core Concepts',
          action: 'Diagram a cluster with nodes, one application, and one service, stopping once each term is correctly placed.',
          recoveryAction: 'Draw a cluster box containing two nodes.', minutes: 25,
          criteria: ['Explain the relationship between cluster, node, application, and service.', 'Label the diagram from memory, without notes.'],
          sourceId: '1.2',
        },
        {
          id: '1-3', title: '1.3 Stateful vs Stateless Services',
          action: 'Compare a stateless API service and a stateful service with local state, stopping once you can state one tradeoff of each.',
          recoveryAction: 'Write one example of each service type.', minutes: 20,
          criteria: ['Explain when to choose a stateless versus a stateful service.', 'Teach back one consequence of choosing the wrong one.'],
          sourceId: '1.3',
        },
        {
          id: '1-4', title: '1.4 Partitions and Replicas',
          action: 'Sketch a partitioned stateful service with a primary and secondary replica, stopping once the roles are labeled correctly.',
          recoveryAction: 'Label one primary and one secondary replica in a sketch.', minutes: 25,
          criteria: ['Explain how partitioning spreads load across a service.', 'Explain the difference between a primary and a secondary replica role.'],
          sourceId: '1.4',
        },
        {
          id: '1-5', title: '1.5 Service Fabric Explorer',
          action: 'Open Service Fabric Explorer against a local cluster, stopping once you can locate its nodes, applications, and services.',
          recoveryAction: 'Open Service Fabric Explorer and find the node list.', minutes: 20,
          criteria: ['Locate nodes, applications, and services in the Explorer UI.', 'Explain what one health indicator in the UI means.'],
          sourceId: '1.5',
        },
        {
          id: '1-6', title: '1.6 Development Environment Setup',
          action: 'Install the Service Fabric SDK and start a local one-node cluster, stopping once it reports healthy.',
          recoveryAction: 'Verify the SDK is installed and start the local cluster.', minutes: 30,
          criteria: ['Confirm the local cluster reports a healthy status.', 'Explain one setup step that commonly fails and why.'],
          sourceId: '1.6',
        },
      ],
    },
    {
      id: 'stage-2-core-development',
      title: 'Stage 2 - Core Development',
      summary: 'Build and experiment: first application, stateless and stateful services, communication, configuration, and local testing.',
      topics: ['First Service Fabric application', 'Stateless service', 'Stateful service', 'Service communication', 'Configuration and settings', 'Local testing'],
      source: { document: FABRIC_DOC, section: 'Section 3: Roadmap - Stage 2 Core Development', page: 2 },
      checkpoints: [
        {
          id: '2-1', title: '2.1 Create Your First Service Fabric Application',
          action: 'Create and deploy a first Service Fabric application to the local cluster, stopping once it runs and appears in Explorer.',
          recoveryAction: 'Scaffold a new Service Fabric application project.', minutes: 30,
          criteria: ['Confirm the application is visible and running in Explorer.', 'Explain what the generated project structure represents.'],
          sourceId: '2.1',
        },
        {
          id: '2-2', title: '2.2 Build a Stateless Service',
          action: 'Build a small stateless REST API service, stopping once it responds correctly to one local request.',
          recoveryAction: 'Add one endpoint that returns a static response.', minutes: 30,
          criteria: ['Confirm the endpoint returns the expected response locally.', 'Explain why this service type holds no local state.'],
          sourceId: '2.2',
        },
        {
          id: '2-3', title: '2.3 Build a Stateful Service',
          action: 'Build a small stateful service using a Reliable Collection, stopping once a value persists across one restart.',
          recoveryAction: 'Write and read one value using a Reliable Dictionary.', minutes: 35,
          criteria: ['Confirm the value survives a local service restart.', 'Explain how a Reliable Collection differs from in-memory state.'],
          sourceId: '2.3',
        },
        {
          id: '2-4', title: '2.4 Service Communication',
          action: 'Connect the stateless and stateful services locally and expose one call from outside the cluster, stopping once both paths succeed.',
          recoveryAction: 'Call one service-to-service endpoint locally.', minutes: 30,
          criteria: ['Confirm an inside-cluster call succeeds between the two services.', 'Confirm one outside-cluster call reaches a service endpoint.'],
          sourceId: '2.4',
        },
        {
          id: '2-5', title: '2.5 Configuration and Settings',
          action: 'Move one hardcoded value into Service Fabric configuration, stopping once changing it alters runtime behavior without a code change.',
          recoveryAction: 'Move one constant into a settings file.', minutes: 25,
          criteria: ['Confirm a configuration change takes effect without redeploying code.', 'Explain the difference between application and service settings.'],
          sourceId: '2.5',
        },
        {
          id: '2-6', title: '2.6 Testing Locally',
          action: 'Simulate one fault, such as stopping a replica, in the local cluster, stopping once you observe and record the recovery behavior.',
          recoveryAction: 'Stop one replica locally and watch Explorer update.', minutes: 30,
          criteria: ['Document the observed recovery behavior after the simulated fault.', 'Explain why the cluster restored service after the fault.'],
          sourceId: '2.6',
        },
      ],
    },
    {
      id: 'stage-3-real-world-application',
      title: 'Stage 3 - Real-World Application',
      summary: 'Apply concepts to migration-style work using generic, sanitized, local examples only.',
      topics: ['Migration architecture', 'Migration components', 'Mapping concepts to work', 'Authorized tasks', 'Documenting learnings', 'Team discussion'],
      source: { document: FABRIC_DOC, section: 'Section 3: Roadmap - Stage 3 Real-World Application', page: 3 },
      checkpoints: [
        {
          id: '3-1', title: '3.1 Understand Current Migration Architecture',
          action: 'Diagram a generic legacy-to-Service-Fabric migration using sanitized, non-identifying service names, stopping once source and target shapes are both represented.',
          recoveryAction: 'Sketch one box for the legacy side and one for Service Fabric.', minutes: 30,
          criteria: ['Explain the high-level shift from the legacy architecture to Service Fabric.', 'Keep all names generic; no employer system names or IDs.'],
          sourceId: '3.1',
        },
        {
          id: '3-2', title: '3.2 Identify Migration Components',
          action: 'List the generic service, dependency, and data categories involved in a Service Fabric migration, using sanitized placeholder names, stopping once each category has one example.',
          recoveryAction: 'Name one generic service and one generic dependency.', minutes: 25,
          criteria: ['Give one sanitized example per component category (service, dependency, data).', 'Explain why each category matters during migration.'],
          sourceId: '3.2',
        },
        {
          id: '3-3', title: '3.3 Map Concepts to Work',
          action: 'Match one earlier Service Fabric concept, such as partitions or stateful services, to a generic description of migration-style work, stopping once the mapping is written down.',
          recoveryAction: 'Write one sentence connecting a concept to a generic task.', minutes: 25,
          criteria: ['Explain how the chosen concept shows up in migration-style work generically.', 'Avoid any employer-specific system name or identifier.'],
          sourceId: '3.3',
        },
        {
          id: '3-4', title: '3.4 Work on Actual Tasks',
          action: 'Complete one authorized, sanitized Service Fabric task, such as code, configuration, or troubleshooting, in an approved local environment, stopping once it is verified working.',
          recoveryAction: 'Reproduce one small, authorized local fix.', minutes: 40,
          criteria: ['Confirm the task is verified working in an approved environment.', 'Issue no cloud commands and use no employer-identifying names here.'],
          sourceId: '3.4',
        },
        {
          id: '3-5', title: '3.5 Document Learnings',
          action: 'Write a short, sanitized note on what worked and one issue resolved during a migration-style task, stopping once it is recorded.',
          recoveryAction: 'Write one sentence on what worked.', minutes: 20,
          criteria: ['Record one thing that worked and one issue resolved, both sanitized.', 'Confirm no private architecture detail or employer identifier is included.'],
          sourceId: '3.5',
        },
        {
          id: '3-6', title: '3.6 Discuss with Team',
          action: 'Prepare three generic questions about design decisions for a team discussion, stopping once you can explain why each question matters.',
          recoveryAction: 'Write one question about a design tradeoff.', minutes: 20,
          criteria: ['State three prepared questions about design decisions.', 'Explain why each question would clarify a tradeoff.'],
          sourceId: '3.6',
        },
      ],
    },
    {
      id: 'stage-4-advanced-topics',
      title: 'Stage 4 - Advanced Topics',
      summary: 'Go deeper: Reliable Collections, fault tolerance/HA, scaling, rolling upgrades, health diagnostics, security, and performance.',
      topics: ['Reliable Collections', 'Fault tolerance & HA', 'Scaling & load balancing', 'Rolling upgrades', 'Health monitoring & diagnostics', 'Security', 'Performance tuning'],
      source: { document: FABRIC_DOC, section: 'Section 3:Roadmap - Stage 4 Advanced Topics', page: 3 },
      checkpoints: [
        {
          id: '4-1', title: '4.1 Reliable Collections',
          action: 'Use a Reliable Queue or a second Reliable Dictionary pattern locally, stopping once a transactional read/write succeeds.',
          recoveryAction: 'Perform one transactional read/write on a Reliable Collection.', minutes: 30,
          criteria: ['Confirm a transactional operation on a Reliable Collection succeeds.', 'Explain one consistency guarantee Reliable Collections provide.'],
          sourceId: '4.1',
        },
        {
          id: '4-2', title: '4.2 Fault Tolerance & High Availability',
          action: 'Simulate a node or replica failure locally and trace the failover, stopping once service availability is confirmed restored.',
          recoveryAction: 'Trigger one local replica failure and observe failover.', minutes: 30,
          criteria: ['Confirm service availability is restored after the simulated failure.', 'Explain the failover sequence that occurred.'],
          sourceId: '4.2',
        },
        {
          id: '4-3', title: '4.3 Scaling & Load Balancing',
          action: 'Add a node to a local cluster and observe service placement, stopping once you can explain how load balanced across nodes.',
          recoveryAction: 'Add one node to the local cluster.', minutes: 30,
          criteria: ['Explain how Service Fabric balances services across nodes.', 'Confirm the added node took on at least one service instance.'],
          sourceId: '4.3',
        },
        {
          id: '4-4', title: '4.4 Rolling Upgrades',
          action: 'Deploy a rolling upgrade to the local sample application, stopping once the upgrade completes or rolls back on a health gate.',
          recoveryAction: 'Start one rolling upgrade on the local application.', minutes: 35,
          criteria: ['Confirm the upgrade completed or correctly rolled back on a failed health check.', 'Explain the purpose of an upgrade domain.'],
          sourceId: '4.4',
        },
        {
          id: '4-5', title: '4.5 Health Monitoring and Diagnostics',
          action: 'Add one custom health report to a local service, stopping once it appears correctly in Explorer.',
          recoveryAction: 'Report one health event from a local service.', minutes: 25,
          criteria: ['Confirm the custom health report is visible in Explorer.', 'Explain how a health report can gate an upgrade.'],
          sourceId: '4.5',
        },
        {
          id: '4-6', title: '4.6 Security',
          action: 'Outline a certificate-based cluster security setup for the local cluster, stopping once you can explain its authentication role.',
          recoveryAction: 'Name one certificate used by the local cluster.', minutes: 30,
          criteria: ['Explain the role of certificates in cluster and node authentication.', 'Describe one risk of a misconfigured or expired certificate.'],
          sourceId: '4.6',
        },
        {
          id: '4-7', title: '4.7 Performance Tuning',
          action: 'Profile one local service under a small synthetic load, stopping once you identify one bottleneck and a mitigation.',
          recoveryAction: 'Run one small synthetic load test locally.', minutes: 35,
          criteria: ['Identify one performance bottleneck from the local profiling run.', 'Propose one concrete mitigation for that bottleneck.'],
          sourceId: '4.7',
        },
      ],
    },
    {
      id: 'stage-5-interview-career',
      title: 'Stage 5 - Interview & Career',
      summary: 'Readiness: project summary, explaining concepts, interview questions, design scenarios, diagrams, mock interviews, and bounded ongoing learning.',
      topics: ['Project summary', 'Explaining key concepts', 'Common interview questions', 'System design scenarios', 'Diagrams', 'Mock interviews', 'Keep learning (bounded)'],
      source: { document: FABRIC_DOC, section: 'Section 3: Roadmap - Stage 5 Interview & Career', page: 3 },
      checkpoints: [
        {
          id: '5-1', title: '5.1 Create a Project Summary',
          action: 'Write a concise project summary positioning your migration-style work as a case study, stopping once it fits in a two-minute spoken pitch.',
          recoveryAction: 'Write the one-sentence headline of your case study.', minutes: 30,
          criteria: ['Confirm the summary delivers in roughly two minutes when spoken.', 'Keep all details generic and sanitized, with no employer identifiers.'],
          sourceId: '5.1',
        },
        {
          id: '5-2', title: '5.2 Be Ready to Explain Key Concepts',
          action: 'Explain one Service Fabric concept at a simple level and then a deep level, stopping once both versions are clear and accurate.',
          recoveryAction: 'Give the one-sentence simple version of one concept.', minutes: 25,
          criteria: ['Deliver a correct simple explanation of the chosen concept.', 'Deliver a correct deep explanation of the same concept on request.'],
          sourceId: '5.2',
        },
        {
          id: '5-3', title: '5.3 Prepare Common Interview Questions',
          action: 'Draft answers to three common Service Fabric architecture and tradeoff interview questions, stopping once each has a clear structure.',
          recoveryAction: 'Write the opening sentence for one answer.', minutes: 30,
          criteria: ['Produce three structured answers covering architecture and tradeoffs.', 'Teach back one answer aloud without reading verbatim.'],
          sourceId: '5.3',
        },
        {
          id: '5-4', title: '5.4 System Design Scenarios',
          action: 'Design a small system using Service Fabric concepts for a generic scenario, stopping once requirements through failure handling are covered.',
          recoveryAction: 'State the requirements for one generic scenario.', minutes: 40,
          criteria: ['Cover requirements, high-level design, and one failure scenario.', 'Explain at least one Service Fabric-specific design choice.'],
          sourceId: '5.4',
        },
        {
          id: '5-5', title: '5.5 Create Diagrams',
          action: 'Draw architecture, data flow, and failover diagrams for your case study, stopping once all three diagrams are complete and consistent.',
          recoveryAction: 'Sketch one architecture box diagram.', minutes: 30,
          criteria: ['Produce consistent architecture, data flow, and failover diagrams.', 'Explain how the diagrams connect to each other.'],
          sourceId: '5.5',
        },
        {
          id: '5-6', title: '5.6 Mock Interviews',
          action: 'Run one technical and one behavioral mock interview round based on this roadmap, stopping once you record one improvement from feedback.',
          recoveryAction: 'Answer one mock interview question aloud.', minutes: 40,
          criteria: ['Complete one technical and one behavioral mock round.', 'Record one concrete improvement identified from feedback.'],
          sourceId: '5.6',
        },
        {
          id: '5-7', title: '5.7 Keep Learning',
          action: 'Review one official Service Fabric or Azure update, release note, or doc change since your last review, stopping once you can summarize what changed.',
          recoveryAction: 'Skim one release-note heading and note the date.', minutes: 20,
          criteria: ['Summarize what changed in the single reviewed update.', 'This is a bounded, single-item review, not an open-ended learning commitment.'],
          sourceId: '5.7',
        },
      ],
    },
  ],
});

export const technicalMissions: Mission[] = [patternMission, systemMission, fabricMission];
